# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plugins1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QRect, Qt
from PyQt5.QtWidgets import QWidget, QPushButton
from plugins import get_all_plugins


class Ui_Form(QWidget):  # Change inheritance to QWidget
    def __init__(self):
        super().__init__()  # Call the QWidget constructor
        self.scrollAreaWidgetContents_2 = None
        self.pluginNames = []
        self.setupUi(self)  # Call setupUi with self as argument

    def setupUi(self, Form):
        Form.setObjectName("Plugins")
        Form.resize(320, 780)

        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 320, 781))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pluginMenulabel = QtWidgets.QLabel(self.frame)
        self.pluginMenulabel.setGeometry(QtCore.QRect(0, 0, 320, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pluginMenulabel.setFont(font)
        self.pluginMenulabel.setCursor(QtGui.QCursor(QtCore.Qt.UpArrowCursor))
        self.pluginMenulabel.setAutoFillBackground(False)
        self.pluginMenulabel.setStyleSheet("background-color: rgb(255, 137, 86);")
        self.pluginMenulabel.setScaledContents(False)
        self.pluginMenulabel.setObjectName("pluginMenulabel")
        self.pluginMenuLabelButton = QtWidgets.QPushButton(self.frame)
        self.pluginMenuLabelButton.setGeometry(QtCore.QRect(280, 10, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.pluginMenuLabelButton.setFont(font)
        self.pluginMenuLabelButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pluginMenuLabelButton.setStyleSheet("background-color: rgb(255, 137, 86);\n"
                                                 "color: rgb(255, 0, 0);")
        self.pluginMenuLabelButton.setDefault(False)
        self.pluginMenuLabelButton.setFlat(True)
        self.pluginMenuLabelButton.setObjectName("pluginMenuLabelButton")
        self.pluginMenuLabelButton.clicked.connect(Form.close)
        self.pluginListWidget = QtWidgets.QListWidget(self.frame)
        self.pluginListWidget.setGeometry(QtCore.QRect(0, 40, 320, 741))
        self.pluginListWidget.setMidLineWidth(-1)
        self.pluginListWidget.setObjectName("pluginListWidget")
        self.pluginScrollArea = QtWidgets.QScrollArea(self.frame)
        self.pluginScrollArea.setGeometry(QtCore.QRect(10, 60, 300, 651))
        self.pluginScrollArea.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                            "border: none;")
        self.pluginScrollArea.setWidgetResizable(True)
        self.pluginScrollArea.setObjectName("pluginScrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 231, 651))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.pluginSelectframe = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.pluginSelectframe.setGeometry(QtCore.QRect(0, 10, 231, 31))
        self.pluginSelectframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.pluginSelectframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pluginSelectframe.setObjectName("pluginSelectframe")

        self.label = QtWidgets.QLabel(self.pluginSelectframe)

        self.pluginMenuLabelButton_2 = QtWidgets.QPushButton(self.pluginSelectframe)
        self.pluginMenuLabelButton_2.setGeometry(QtCore.QRect(60, 5, 35, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)

        self.pluginScrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.pluginSaveButton = QtWidgets.QPushButton(self.pluginSelectframe)
        self.pluginSaveButton.setGeometry(QtCore.QRect(120, 740, 75, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pluginSaveButton.setFont(font)
        self.pluginSaveButton.setStyleSheet("background-color: rgb(255, 137, 86);\n"
                                            "border-radius: 5px;\n"
                                            "border: 1px solid black;")
        self.pluginSaveButton.setObjectName("pluginSaveButton")
        self.pluginAddButton = QtWidgets.QPushButton(self.frame)
        self.pluginAddButton.setGeometry(QtCore.QRect(100, 710, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pluginAddButton.setFont(font)
        self.pluginAddButton.setToolTipDuration(1)
        self.pluginAddButton.setStyleSheet("background-color: rgb(255, 137, 86);\n"
                                           "border-radius: 5px;\n"
                                           "border: 1px solid black;")
        self.pluginAddButton.setObjectName("pluginAddButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        # Get the list of plugins from plugins.py
        plugin_data = get_all_plugins()
        self.pluginNames = [f"{os_name}.{plugin}" for os_name, plugins in plugin_data for plugin in plugins]

        # Call the function to create the widgets
        self.createPluginWidgets(self.pluginScrollArea, self.pluginNames)

        # Call the function to create the widgets
        self.createPluginWidgets(self.pluginScrollArea, self.pluginNames)

    def createPluginWidgets(self, scrollArea, pluginNames):
        # Create a QWidget and a QVBoxLayout
        scrollWidget = QtWidgets.QWidget()
        scrollLayout = QtWidgets.QVBoxLayout()

        # Set the spacing between the widgets in the QVBoxLayout
        scrollLayout.setSpacing(0)  # Adjust this value to increase or decrease the space

        # Iterate over the plugin names
        for name in pluginNames:
            # Create a new block of code for each plugin
            _translate = QtCore.QCoreApplication.translate

            # Create a new frame for each plugin
            pluginSelectframe = QtWidgets.QFrame()
            pluginSelectframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
            pluginSelectframe.setFrameShadow(QtWidgets.QFrame.Raised)
            pluginSelectframe.setObjectName(name + "Selectframe")

            # Create a new checkbox for each plugin
            pluginCheckBox = QtWidgets.QCheckBox(pluginSelectframe)
            pluginCheckBox.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
            pluginCheckBox.setText("")
            pluginCheckBox.setObjectName(name + "CheckBox")

            # Create a new label for each plugin
            label = QtWidgets.QLabel(pluginSelectframe)
            label.setObjectName(name + "Label")
            label.setText(_translate("Plugins", name))

            # Create a close button for each plugin
            pluginMenuLabelButton_2 = QtWidgets.QPushButton(pluginSelectframe)
            font = QtGui.QFont()
            font.setFamily("Arial")
            font.setPointSize(10)  # Reduce the font size
            pluginMenuLabelButton_2.setFont(font)
            # pluginMenuLabelButton_2.setFocusPolicy(QtCore.Qt.NoFocus)
            pluginMenuLabelButton_2.setStyleSheet("color: rgb(255, 137, 86);\n"
                                                  )
            pluginMenuLabelButton_2.setDefault(False)
            pluginMenuLabelButton_2.setFlat(True)
            pluginMenuLabelButton_2.setObjectName(name + "MenuLabelButton_2")

            # Create a layout for the frame
            frameLayout = QtWidgets.QHBoxLayout()
            frameLayout.addWidget(pluginCheckBox)
            frameLayout.addWidget(label)
            frameLayout.addWidget(pluginMenuLabelButton_2)

            # Set the layout to the frame
            pluginSelectframe.setLayout(frameLayout)

            # Add the frame to the QVBoxLayout
            scrollLayout.addWidget(pluginSelectframe)

        # Set the layout to the QWidget
        scrollWidget.setLayout(scrollLayout)

        # Set the QWidget as the widget for the QScrollArea
        scrollArea.setWidget(scrollWidget)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Plugins", "Plugins"))

        self.pluginMenulabel.setText(_translate("Plugins", "  Plugins"))
        self.pluginMenuLabelButton.setText(_translate("Plugins", "X"))
        self.label.setText(_translate("Plugins", "Pluginname.PluginName"))
        self.pluginMenuLabelButton_2.setText(_translate("Plugins", "X"))
        self.pluginSaveButton.setText(_translate("Plugins", "Save"))
        self.pluginAddButton.setText(_translate("Plugins", "+"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
